### ISSUE TITLE
Usage with Jest

### ISSUE THREAD

**Issue by kavsingh** [ncthis/saul#4]
Hey, this looks really good, trying to use it with an exisiting project which uses Jest but am unsure how to make that work, or if it does atm.

In a file in `./src`:
```javascript
...
// @t "should add numbers" add(1, 2) equals 3
export const add = (a, b) => a + b
...
```

`.saulrc`:
```json
{
    "fileGlob": "src/**/*.js"
}
```

scripts in `package.json`:
```json
...
"test": "NODE_ENV=test jest --config jest.config.json --verbose node_modules/.bin/saul",
...
```

outcome:
```bash
❯ npm t

> sauling@1.0.0 test /Users/kav/Sites/playground/sauling
> NODE_ENV=test jest --config jest.config.json --verbose node_modules/.bin/saul

No tests found
In /Users/kav/Sites/playground/sauling
  10 files checked.
  testMatch:  - 10 matches
  testPathIgnorePatterns: /node_modules/ - 10 matches
  testRegex: \.test\.js$ - 1 match
Pattern: "node_modules/.bin/saul" - 0 matches
```

so it seems the jest cli uses that last bit of the command to look for matching tests. Same thing happens if i take `node_modules/.bin/saul` out of the npm script and run `npm t node_modules/.bin/saul`. `npm t | node_modules/.bin/saul` hail mary is all errors:

```bash
/Users/kav/Sites/playground/sauling/node_modules/saul/lib/testcase.js:6
var suite = exports.suite = describe;
                            ^

ReferenceError: describe is not defined
```

 Is anything in the Jest config that can be set up for it to work?

Thanks heaps!

**Comment by ncthis** [comment]
Thanks for the feedback @kavsingh! I will look at this and try to give a concrete fix in a few hours. Can you provide a sample structure of your `jest.config.json`?

**Comment by kavsingh** [comment]
Hey, no problem!

Here's my jest config:
```json
{
  "testRegex": "\\.test\\.js$",
  "coverageDirectory": "<rootDir>/coverage/",
  "collectCoverageFrom": ["src/**/*.js"],
  "coveragePathIgnorePatterns": ["<rootDir>/dist/", "<rootDir>/node_modules/"],
  "moduleNameMapper": {
    "^.+\\.css$": "identity-obj-proxy",
    "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__testMocks__/fileMock.js"
  }
}
```

**Comment by ncthis** [comment]
Ok, figured this out. Since jest requires a testRegex, and not a test file, supplying the executable does not seem to work.

But you can create a one-line file that matches your `testRegex` and put `require('saul')` there. It should then run as expected.

I've updated the docs to reflect this as well: https://github.com/ncthis/saul#jest

Thanks for reporting this @kavsingh. Let me know if you need more help on this issue, or if we can close this.

**Comment by kavsingh** [comment]
Worked great! I think this can be closed, look forward to trying this in more depth. Thanks!
